spring.datasource:
  driver-class-name: net.ucanaccess.jdbc.UcanaccessDriver
#  url: jdbc:ucanaccess://c:/wk/demo.accdb;memory=false;newDatabaseVersion=V2007
  url: jdbc:ucanaccess://demo.accdb;memory=false;newDatabaseVersion=V2007
#  validationQuery: SELECT 1
  testOnBorrow: true
  hikari:
    pool-name: ConnectionPool
    leakDetectionThreshold: 5000
#    connection-test-query: SELECT 1
    minimum-idle: 5
    maximum-pool-size: 10
    auto-commit: false

 # MyBatisの設定
mybatis:
  # SQL項目(主にSELECT句)のアンダースコアをキャメルケースに変換して自動マッピングするための設定
  configuration:
    map-underscore-to-camel-case: true

# Jackson ObjectMapper
spring.jackson.visibility:
  field: any
  getter: none
  is-getter: none
  setter: none

logging.level.*: DEBUG 
  